# Generated by Django 3.2.9 on 2021-12-10 20:45

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuluPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=1, verbose_name='Indeks')),
                ('author', models.CharField(blank=True, max_length=40, null=True, verbose_name='Autor')),
                ('title', models.CharField(max_length=60, verbose_name='Tytuł')),
                ('content', models.TextField(verbose_name='Twój Post')),
                ('lulu_pic', models.ImageField(blank=True, null=True, upload_to='lulu_images/', verbose_name='Zdjęcie')),
                ('pic_caption', models.CharField(blank=True, max_length=35, null=True, verbose_name='Podpis')),
                ('publ_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data publikacji')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=1, verbose_name='Indeks')),
                ('author', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Wpisz przynajmniej 2 znaki w polu AUTOR.')], verbose_name='Autor')),
                ('pet_name', models.CharField(max_length=40, verbose_name='Imię zwierzaka')),
                ('pet_species', models.CharField(choices=[('Pies', 'Pies'), ('Kot', 'Kot'), ('Chomik', 'Chomik'), ('Królik', 'Królik'), ('Żółw', 'Żółw'), ('Papuga', 'Papuga'), ('Świnka morska', 'Świnka morska'), ('Rybki', 'Rybki'), ('Mysz', 'Mysz'), ('Szczur', 'Szczur'), ('Jaszczurka', 'Jaszczurka'), ('Inny gatunek', 'Inny gatunek')], default=None, max_length=20, verbose_name='Wybierz gatunek')),
                ('pet_species_other', models.CharField(blank=True, max_length=30, null=True, verbose_name='Inny gatunek')),
                ('title', models.CharField(max_length=60, verbose_name='Tytuł')),
                ('content', models.TextField(verbose_name='Twój Post')),
                ('lulu_pic', models.ImageField(blank=True, null=True, upload_to='lulu_images/', verbose_name='Zdjęcie')),
                ('pic_caption', models.CharField(blank=True, max_length=35, null=True, verbose_name='Podpis')),
                ('e_mail', models.EmailField(max_length=50, verbose_name='Adres e-mail')),
                ('publ_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data publikacji')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść komentarza')),
                ('publ_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data dodania')),
                ('active', models.BooleanField(default=True)),
                ('rate', models.IntegerField(choices=[(1, 'Lulu Rozczarowana'), (2, 'Lulu Marudna'), (3, 'Lulu Zainteresowana'), (4, 'Lulu Pobudzona'), (5, 'Lulu Podekscytowana')])),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lulublog.petpost', verbose_name='Komentarz')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor komentarza')),
            ],
            options={
                'ordering': ('-publ_date',),
            },
        ),
        migrations.CreateModel(
            name='LuluPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść komentarza')),
                ('publ_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data dodania')),
                ('active', models.BooleanField(default=True)),
                ('rate', models.IntegerField(choices=[(1, 'Lulu Rozczarowana'), (2, 'Lulu Marudna'), (3, 'Lulu Zainteresowana'), (4, 'Lulu Pobudzona'), (5, 'Lulu Podekscytowana')])),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lulublog.lulupost', verbose_name='Komentarz')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor komentarza')),
            ],
            options={
                'ordering': ('-publ_date',),
            },
        ),
    ]
