# Generated by Django 3.2.9 on 2021-12-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lulublog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lulupostcomment',
            old_name='user',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='petpostcomment',
            old_name='user',
            new_name='name',
        ),
    ]
