# Generated by Django 3.2.9 on 2021-12-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulublog', '0003_auto_20211212_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lulupost',
            name='publ_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data publikacji'),
        ),
        migrations.AlterField(
            model_name='lulupostcomment',
            name='publ_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='publ_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data publikacji'),
        ),
        migrations.AlterField(
            model_name='petpostcomment',
            name='publ_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania'),
        ),
    ]
