# Generated by Django 3.2.9 on 2021-12-12 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lulublog', '0004_auto_20211212_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lulupost',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lulu_post_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_post_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
