# Generated by Django 3.2.9 on 2021-12-12 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lulublog', '0007_auto_20211212_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lulupostcomment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='petpostcomment',
            name='name',
        ),
        migrations.AddField(
            model_name='lulupostcomment',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor komentarza'),
        ),
        migrations.AddField(
            model_name='petpostcomment',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor komentarza'),
        ),
    ]
