# Generated by Django 3.2.9 on 2021-12-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulublog', '0008_auto_20211212_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lulupostcomment',
            name='rate',
            field=models.CharField(choices=[('1', 'LULU_ROZCZAROWANA'), ('2', 'LULU_MARUDNA'), ('3', 'LULU_ZAINTERESOWANA'), ('4', 'LULU_POBUDZONA'), ('5', 'LULU_PODEKSCYTOWANA')], default=None, max_length=30, verbose_name='Ocena'),
        ),
        migrations.AlterField(
            model_name='petpostcomment',
            name='rate',
            field=models.CharField(choices=[('1', 'LULU_ROZCZAROWANA'), ('2', 'LULU_MARUDNA'), ('3', 'LULU_ZAINTERESOWANA'), ('4', 'LULU_POBUDZONA'), ('5', 'LULU_PODEKSCYTOWANA')], default=None, max_length=30, verbose_name='Ocena'),
        ),
    ]
