# Generated by Django 3.2.9 on 2021-12-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulublog', '0009_auto_20211215_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lulupostcomment',
            name='rate',
            field=models.CharField(choices=[('Lulu rozczarowana', 'LULU_ROZCZAROWANA'), ('Lulu marudna', 'LULU_MARUDNA'), ('Lulu zainteresowana', 'LULU_ZAINTERESOWANA'), ('Lulu pobudzona', 'LULU_POBUDZONA'), ('Lulu podekscytowana', 'LULU_PODEKSCYTOWANA')], default=None, max_length=30, verbose_name='Ocena'),
        ),
        migrations.AlterField(
            model_name='petpostcomment',
            name='rate',
            field=models.CharField(choices=[('Lulu rozczarowana', 'LULU_ROZCZAROWANA'), ('Lulu marudna', 'LULU_MARUDNA'), ('Lulu zainteresowana', 'LULU_ZAINTERESOWANA'), ('Lulu pobudzona', 'LULU_POBUDZONA'), ('Lulu podekscytowana', 'LULU_PODEKSCYTOWANA')], default=None, max_length=30, verbose_name='Ocena'),
        ),
    ]
