# Generated by Django 3.2.9 on 2021-12-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulublog', '0011_auto_20211215_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lulupostcomment',
            name='rate',
            field=models.CharField(choices=[('1 * Lulu rozczarowana', 'LULU ROZCZAROWANA'), ('2 ** Lulu marudna', 'LULU MARUDNA'), ('3 *** Lulu zainteresowana', 'LULU ZAINTERESOWANA'), ('4 **** Lulu pobudzona', 'LULU POBUDZONA'), ('5 ***** Lulu podekscytowana', 'LULU PODEKSCYTOWANA')], default=None, max_length=30, verbose_name='Ocena'),
        ),
        migrations.AlterField(
            model_name='petpostcomment',
            name='rate',
            field=models.CharField(choices=[('1 * Lulu rozczarowana', 'LULU_ROZCZAROWANA'), ('2 ** Lulu marudna', 'LULU_MARUDNA'), ('3 *** Lulu zainteresowana', 'LULU_ZAINTERESOWANA'), ('4 **** Lulu pobudzona', 'LULU_POBUDZONA'), ('5 ***** Lulu podekscytowana', 'LULU_PODEKSCYTOWANA')], default=None, max_length=30, verbose_name='Ocena'),
        ),
    ]
