# Generated by Django 3.2.9 on 2021-12-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulublog', '0012_auto_20211215_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lulupostcomment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='petpostcomment',
            name='active',
        ),
        migrations.AlterField(
            model_name='lulupostcomment',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Treść komentarza'),
        ),
        migrations.AlterField(
            model_name='lulupostcomment',
            name='rate',
            field=models.CharField(choices=[('1 * Lulu rozczarowana', ' 1 * LULU ROZCZAROWANA'), ('2 ** Lulu marudna', ' 2 ** LULU MARUDNA'), ('3 *** Lulu zainteresowana', ' 3 *** LULU ZAINTERESOWANA'), ('4 **** Lulu pobudzona', ' 4 **** POBUDZONA'), ('5 ***** Lulu podekscytowana', ' 5 ***** LULU PODEKSCYTOWANA')], default=None, max_length=30, verbose_name='Ocena'),
        ),
        migrations.AlterField(
            model_name='petpostcomment',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Treść komentarza'),
        ),
        migrations.AlterField(
            model_name='petpostcomment',
            name='rate',
            field=models.CharField(choices=[('1 * Lulu rozczarowana', ' 1 * ROZCZAROWANA'), ('2 ** Lulu marudna', ' 2 ** LULU MARUDNA'), ('3 *** Lulu zainteresowana', ' 3 *** LULU ZAINTERESOWANA'), ('4 **** Lulu pobudzona', ' 4 **** LULU POBUDZONA'), ('5 ***** Lulu podekscytowana', ' 5 ***** LULU PODEKSCYTOWANA')], default=None, max_length=30, verbose_name='Ocena'),
        ),
    ]
