# Generated by Django 3.2.9 on 2021-12-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulublog', '0013_auto_20211216_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lulupost',
            name='index',
        ),
        migrations.RemoveField(
            model_name='petpost',
            name='index',
        ),
        migrations.AlterField(
            model_name='petpostcomment',
            name='rate',
            field=models.CharField(choices=[('1 * Lulu rozczarowana', ' 1 * LULU ROZCZAROWANA'), ('2 ** Lulu marudna', ' 2 ** LULU MARUDNA'), ('3 *** Lulu zainteresowana', ' 3 *** LULU ZAINTERESOWANA'), ('4 **** Lulu pobudzona', ' 4 **** LULU POBUDZONA'), ('5 ***** Lulu podekscytowana', ' 5 ***** LULU PODEKSCYTOWANA')], default=None, max_length=30, verbose_name='Ocena'),
        ),
    ]
